### ISSUE TITLE
Crash running Farseer if misspell in aminoacid 3-letter code 

### ISSUE THREAD

**Issue by hector-fs** [Farseer-NMR/FarSeer-NMR#267]
After clicking "Run FarSeer-NMR" if some peaklists contains a misspelled residue, FarSeer crashes, printing the following error in the console:

```
Traceback (most recent call last):
  File "/home/admin/FarSeer-NMR/gui/components/TabWidget.py", line 257, in run_farseer_calculation
    create_directory_structure(output_path, self.variables)
  File "/home/admin/FarSeer-NMR/core/setup_farseer_calculation.py", line 141, in create_directory_structure
    write_peaklist_file(fout, peaklist)
  File "/home/admin/FarSeer-NMR/core/setup_farseer_calculation.py", line 172, in write_peaklist_file
    "".join([peak.residue_number, peak.residue_type, peak.atoms[0]]),
IndexError: list index out of range
./run_farseer.sh: line 6:  7122 Aborted                 (core dumped) python $FARSEER_ROOT/gui/main.py $*
```

**Comment by joaomcteixeira** [comment]
Hi,
thanks for reporting.
Have you identified the peaklist that is giving the error? Can you send it
to farseer.nmr@gmail.com? please use the number of this issue as email
subject.
we will address asap.

**Comment by joaomcteixeira** [comment]
Similar to #258 
registered in project and to be addressed
closing for now
