### ISSUE TITLE
Side chains finding missing

### ISSUE THREAD

**Issue by joaomcteixeira** [Farseer-NMR/FarSeer-NMR#283]
When analysing peaklists with sidechains it requires that the peaklists have at least one sidechain. If within the data set some peaklists have sidechain information and other don't it crashes with the following error:

```
Traceback (most recent call last):
  File "/home/joao/Programming/farseer_fork/core/farseermain.py", line 1923, in <module>
    farseer.run()
  File "/home/joao/Programming/farseer_fork/core/farseermain.py", line 1785, in run
    self.finds_missing_residues(resonance_type='Sidechains')
  File "/home/joao/Programming/farseer_fork/core/farseermain.py", line 867, in finds_missing_residues
    resonance_type=resonance_type
  File "/home/joao/Programming/farseer_fork/core/fslibs/FarseerCube.py", line 1194, in finds_missing
    ref_pkl.copy(),
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by joaomcteixeira** [comment]
added to project,
To be addressed,
